# Generated by Django 2.1.7 on 2019-02-16 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('messages', models.CharField(blank=True, max_length=500)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
